[build]
  base = "frontend/webapp"
  command = "CI= npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  base = "frontend/webapp"
  command = "npm start"
  port = 8888
  targetPort = 3001
  publish = "build"
  functionsPort = 9000

# セキュリティヘッダーの設定
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://accounts.google.com https://apis.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.amazonaws.com https://accounts.google.com https://apis.google.com; frame-src https://accounts.google.com"

# Functions へのアクセス許可設定
[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-CSRF-Token, X-Session-Id"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# API経由でFunctionsにアクセス
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Alpaca APIプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/alpaca-api-proxy"
  to = "/.netlify/functions/alpaca-api-proxy"
  status = 200
  force = true

# Yahoo Finance APIプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/yahoo-finance-proxy"
  to = "/.netlify/functions/yahoo-finance-proxy"
  status = 200
  force = true

# 元の為替レートプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/exchangerate-proxy"
  to = "/.netlify/functions/exchangerate-proxy"
  status = 200
  force = true

# 代替為替レートプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/alternative-exchangerate-proxy"
  to = "/.netlify/functions/alternative-exchangerate-proxy"
  status = 200
  force = true

# 日本株スクレイピングプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/jp-stock-scraping-proxy"
  to = "/.netlify/functions/jp-stock-scraping-proxy"
  status = 200
  force = true

# 投資信託スクレイピングプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/mutual-fund-scraping-proxy"
  to = "/.netlify/functions/mutual-fund-scraping-proxy"
  status = 200
  force = true

# SPAのためのリダイレクト
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 株価スクレイピングプロキシのリダイレクト設定
[[redirects]]
  from = "/api/stock-scraping-proxy"
  to = "/.netlify/functions/stock-scraping-proxy"
  status = 200
  force = true
  
# Functions 設定
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]