[build]
  command = "CI= npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
  publish = "build"
  functionsPort = 9000

# Functions へのアクセス許可設定
[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# API経由でFunctionsにアクセス
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Alpaca APIプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/alpaca-api-proxy"
  to = "/.netlify/functions/alpaca-api-proxy"
  status = 200
  force = true

# Yahoo Finance APIプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/yahoo-finance-proxy"
  to = "/.netlify/functions/yahoo-finance-proxy"
  status = 200
  force = true

# 元の為替レートプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/exchangerate-proxy"
  to = "/.netlify/functions/exchangerate-proxy"
  status = 200
  force = true

# 代替為替レートプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/alternative-exchangerate-proxy"
  to = "/.netlify/functions/alternative-exchangerate-proxy"
  status = 200
  force = true

# 日本株スクレイピングプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/jp-stock-scraping-proxy"
  to = "/.netlify/functions/jp-stock-scraping-proxy"
  status = 200
  force = true

# 投資信託スクレイピングプロキシ向けのリダイレクト
[[redirects]]
  from = "/api/mutual-fund-scraping-proxy"
  to = "/.netlify/functions/mutual-fund-scraping-proxy"
  status = 200
  force = true

# SPAのためのリダイレクト
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions 設定
[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["functions/**"]
