name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd frontend/webapp
          npm install --legacy-peer-deps
          npm install ajv@8 --legacy-peer-deps
          
      - name: Build
        run: |
          cd frontend/webapp
          echo "Building with environment variables:"
          echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL"
          echo "REACT_APP_DEFAULT_EXCHANGE_RATE=$REACT_APP_DEFAULT_EXCHANGE_RATE"
          NODE_OPTIONS='--openssl-legacy-provider' npm run build
        env:
          REACT_APP_API_BASE_URL: 'https://gglwlh6sc7.execute-api.us-west-2.amazonaws.com/prod'
          REACT_APP_DEFAULT_EXCHANGE_RATE: '150.0'
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy frontend/webapp/build --project-name=pfwise-portfolio-manager --branch=main --commit-hash=${{ github.sha }} --commit-message="${{ github.event.head_commit.message }}"
          
      - name: Show deployment info
        run: |
          echo "Deployment should be available at:"
          echo "Production: https://portfolio-wise.com"
          echo "Please check Cloudflare Dashboard for deployment status"